; LLVM IR generated by yidi
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

%yk_string = type { ptr, i64 }

declare void @yk_print_int(i64)
declare void @yk_print_real(double)
declare void @yk_print_bool(i1)
declare void @yk_print_str_ptr(ptr)
declare ptr @yk_string_from_int(i64)
declare ptr @yk_string_concat_ptr(ptr, ptr)
declare i64 @yk_string_len_ptr(ptr)

define i64 @add(i64, i64) {
  %a.ptr = alloca i64, align 8
  store i64 %0, ptr %a.ptr
  %b.ptr = alloca i64, align 8
  store i64 %1, ptr %b.ptr
  %a.val_0 = load i64, ptr %a.ptr
  %b.val_1 = load i64, ptr %b.ptr
  %yk_2 = add i64 %a.val_0, %b.val_1
  ret i64 %yk_2
  ret i64 0
}

define i32 @main(i32 %argc, ptr %argv) {
  %yk_3 = alloca i32, align 4
  store i32 %argc, ptr %yk_3
  %x.ptr = alloca i64, align 8
  %yk_4 = call i64 @add(i64 3, i64 4)
  store i64 %yk_4, ptr %x.ptr
  %x.val_5 = load i64, ptr %x.ptr
  call void @yk_print_int(i64 %x.val_5)
  %x.val_6 = load i64, ptr %x.ptr
  %yk_7 = add i64 %x.val_6, 10
  call void @yk_print_int(i64 %yk_7)
  %x.val_8 = load i64, ptr %x.ptr
  %x.val_9 = load i64, ptr %x.ptr
  %yk_10 = call i64 @add(i64 %x.val_8, i64 %x.val_9)
  call void @yk_print_int(i64 %yk_10)
  ret i32 0
}
