; LLVM IR generated by yidi
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

%yk_string = type { ptr, i64 }

declare void @yk_print_int(i64)
declare void @yk_print_real(double)
declare void @yk_print_bool(i1)
declare void @yk_print_str_ptr(ptr)
declare ptr @yk_string_from_int(i64)
declare ptr @yk_string_concat_ptr(ptr, ptr)
declare i64 @yk_string_len_ptr(ptr)

define i32 @main(i32 %argc, ptr %argv) {
  %yk_0 = alloca i32, align 4
  store i32 %argc, ptr %yk_0
  %x.ptr = alloca i64, align 8
  %yk_1 = add i64 5, 12
  store i64 %yk_1, ptr %x.ptr
  %yk_3 = alloca %yk_string, align 8
  %yk_4 = getelementptr inbounds %yk_string, ptr %yk_3, i64 0, i32 0
  store ptr @yk_2, ptr %yk_4
  %yk_5 = getelementptr inbounds %yk_string, ptr %yk_3, i64 0, i32 1
  store i64 2, ptr %yk_5
  %x.val_6 = load i64, ptr %x.ptr
  call void @yk_print_str_ptr(ptr %yk_3)
  call void @yk_print_int(i64 %x.val_6)
  ret i32 0
}
@yk_2 = private unnamed_addr constant [3 x i8] c"t:\00", align 1
