; LLVM IR generated by yidi
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

%yk_string = type { ptr, i64 }

declare void @yk_print_int(i64)
declare void @yk_print_real(double)
declare void @yk_print_bool(i1)
declare void @yk_print_str_ptr(ptr)
declare ptr @yk_string_from_int(i64)
declare ptr @yk_string_concat_ptr(ptr, ptr)
declare i64 @yk_string_len_ptr(ptr)

define i32 @main(i32 %argc, ptr %argv) {
  %yk_0 = alloca i32, align 4
  store i32 %argc, ptr %yk_0
  %x.ptr = alloca i64, align 8
  %yk_1 = add i64 5, 10
  store i64 %yk_1, ptr %x.ptr
  %y.ptr = alloca i64, align 8
  %x.val_2 = load i64, ptr %x.ptr
  %yk_3 = mul i64 %x.val_2, 2
  store i64 %yk_3, ptr %y.ptr
  %y.val_4 = load i64, ptr %y.ptr
  call void @yk_print_int(i64 %y.val_4)
  %x.val_8 = load i64, ptr %x.ptr
  %yk_9 = icmp sgt i64 %x.val_8, 10
  br i1 %yk_9, label %yk_5, label %yk_6
yk_5:
    call void @yk_print_int(i64 1)
    br label %yk_7
yk_6:
    call void @yk_print_int(i64 0)
    br label %yk_7
yk_7:
  ret i32 0
}
