; LLVM IR generated by yidi
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

%yk_string = type { ptr, i64 }

declare void @yk_print_int(i64)
declare void @yk_print_real(double)
declare void @yk_print_bool(i1)
declare void @yk_print_str_ptr(ptr)
declare ptr @yk_string_from_int(i64)
declare ptr @yk_string_concat_ptr(ptr, ptr)
declare i64 @yk_string_len_ptr(ptr)

define i32 @main(i32 %argc, ptr %argv) {
  %yk_0 = alloca i32, align 4
  store i32 %argc, ptr %yk_0
  %x.ptr = alloca double, align 8
  store double 3.14, ptr %x.ptr
  %y.ptr = alloca double, align 8
  store double 2.71, ptr %y.ptr
  %x.val_1 = load double, ptr %x.ptr
  %y.val_2 = load double, ptr %y.ptr
  %yk_3 = fadd double %x.val_1, %y.val_2
  call void @yk_print_real(double %yk_3)
  %x.val_4 = load double, ptr %x.ptr
  %y.val_5 = load double, ptr %y.ptr
  %yk_6 = fmul double %x.val_4, %y.val_5
  call void @yk_print_real(double %yk_6)
  ret i32 0
}
