; LLVM IR generated by yidi
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

%yk_string = type { ptr, i64 }

declare void @yk_print_int(i64)
declare void @yk_print_real(double)
declare void @yk_print_bool(i1)
declare void @yk_print_str_ptr(ptr)
declare ptr @yk_string_from_int(i64)
declare ptr @yk_string_concat_ptr(ptr, ptr)
declare i64 @yk_string_len_ptr(ptr)

define i32 @main(i32 %argc, ptr %argv) {
  %yk_0 = alloca i32, align 4
  store i32 %argc, ptr %yk_0
  %i.ptr = alloca i64, align 8
  store i64 0, ptr %i.ptr
  br label %yk_1
yk_1:
  %i.val_4 = load i64, ptr %i.ptr
  %yk_5 = icmp slt i64 %i.val_4, 5
  br i1 %yk_5, label %yk_2, label %yk_3
yk_2:
    %i.val_6 = load i64, ptr %i.ptr
    call void @yk_print_int(i64 %i.val_6)
    %i.val_7 = load i64, ptr %i.ptr
    %yk_8 = add i64 %i.val_7, 1
    store i64 %yk_8, ptr %i.ptr
    br label %yk_1
yk_3:
  ret i32 0
}
