; LLVM IR generated by yidi
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

%yk_string = type { ptr, i64 }
%yk_complex = type { double, double }
%yk_variant = type { i64, i64 }


declare void @yk_print_int(i64)
declare void @yk_print_real(double)
declare void @yk_print_bool(i1)
declare void @yk_print_str_ptr(ptr)
declare ptr @yk_string_from_int(i64)
declare ptr @yk_string_from_real(double)
declare ptr @yk_string_from_bool(i1)
declare ptr @yk_string_from_complex(ptr)
declare ptr @yk_string_concat_ptr(ptr, ptr)
declare i64 @yk_string_len_ptr(ptr)
declare void @yk_complex_set(ptr, double, double)
declare double @yk_complex_real(ptr)
declare double @yk_complex_imag(ptr)
declare double @yk_complex_mod(ptr)
declare double @yk_complex_arg(ptr)
declare void @yk_complex_conj(ptr, ptr)
declare void @yk_complex_add(ptr, ptr, ptr)
declare void @yk_complex_sub(ptr, ptr, ptr)
declare void @yk_complex_mul(ptr, ptr, ptr)
declare void @yk_complex_div(ptr, ptr, ptr)
declare void @yk_print_complex(ptr)
declare i64 @yk_run_thread(ptr, ptr)
declare i64 @yk_join_thread(i64)
declare void @yk_task_set_result(i64, i64)
declare i64 @yk_math_abs_i64(i64)
declare double @yk_math_abs_real(double)
declare double @yk_math_sqrt(double)
declare double @yk_math_sin(double)
declare double @yk_math_cos(double)
declare double @yk_math_floor(double)
declare double @yk_math_ceil(double)
declare double @yk_math_round(double)
declare double @yk_math_pow(double, double)
declare double @yk_math_max(double, double)
declare double @yk_math_min(double, double)
declare i64 @yk_math_rand(i64)

define i32 @main(i32 %argc, ptr %argv) {
  %yk_0 = alloca i32, align 4
  store i32 %argc, ptr %yk_0
  call void @yk_print_int(i64 42)
  ret i32 0
}
