#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Fn, Const, If, Else, For, In, While, Loop, Infiny, Return,
    Struct, Class, Interface, Union, Enum, Object, Type, Use, Export, As, From,
    Async, Await, Spawn, Try, Catch, Init, Open, Abstract, Data, Override, Final, True, False, Null, None, Mut, Ref, Match, Super,
    OkKw, ErrorKw,
    TInt(u8), TRint(u8), TReal(u8), TComplex, TBool, TStr, TSymbol, TVector, TMatrix, TMap,
    IntLit(String), HexLit(String), RealLit(String),
    ImagInt(String), ImagReal(String),
    StrLit(String), SymbolLit(String), CharLit(char),
    BacktickStr(String), FStrLit(String),
    Ident(String),
    Plus, Minus, Star, Slash, Percent, StarStar, Caret, Tilde, Eq, EqEq, NotEq,
    Lt, Gt, LtEq, GtEq, Shl, Shr, Bang, And, Or, Pipe, Inc, Dec,
    PlusEq, MinusEq, StarEq, SlashEq, PercentEq, StarStarEq,
    PipeEq, RefEq, CaretEq, ShlEq, ShrEq,
    Question, QuestionDot, Elvis, Arrow, FatArrow,
    LParen, RParen, LBrace, RBrace, LBracket, RBracket,
    Colon, DoubleColon, Semicolon, Comma, Dot, DotDot, DotDotDot, At, Hash,
    Error(String), Eof,
}
